import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "ArguFight terms of service and user agreement.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: February 2026
      </p>
      <div className="prose prose-invert mt-8 max-w-none space-y-6 text-muted-foreground">
        <p>
          By accessing and using ArguFight, you agree to be bound by these Terms
          of Service. If you do not agree, please do not use the platform.
        </p>
        <h2 className="text-lg font-semibold text-foreground">
          1. Account Registration
        </h2>
        <p>
          You must provide accurate information when creating an account. You are
          responsible for maintaining the security of your account credentials.
        </p>
        <h2 className="text-lg font-semibold text-foreground">
          2. Acceptable Use
        </h2>
        <p>
          You agree to use ArguFight for lawful purposes only. Debates must focus
          on the topic at hand. Personal attacks, harassment, hate speech, and
          threats are strictly prohibited.
        </p>
        <h2 className="text-lg font-semibold text-foreground">
          3. AI Judging
        </h2>
        <p>
          Verdicts are generated by AI models and represent automated analysis of
          debate arguments. While we strive for fairness, AI verdicts are not
          infallible and should not be considered authoritative rulings.
        </p>
        <h2 className="text-lg font-semibold text-foreground">
          4. Content Ownership
        </h2>
        <p>
          You retain ownership of arguments you submit. By posting on ArguFight,
          you grant us a license to display, distribute, and promote your content
          on the platform.
        </p>
        <h2 className="text-lg font-semibold text-foreground">
          5. Subscriptions & Payments
        </h2>
        <p>
          Pro subscriptions are billed monthly or annually via Stripe. You may
          cancel at any time. Refunds are handled on a case-by-case basis.
        </p>
        <h2 className="text-lg font-semibold text-foreground">
          6. Termination
        </h2>
        <p>
          We reserve the right to suspend or terminate accounts that violate
          these terms or engage in abusive behavior.
        </p>
      </div>
    </div>
  );
}
